name: legacy-alterschema
on:
  push:
    branches:
      - main
    paths:
      - legacy/**
  pull_request:
    paths:
      - legacy/**

concurrency:
  group: legacy-${{ github.ref }}
  cancel-in-progress: true
jobs:
  legacy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: make -C legacy

  legacy-website:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt-get install --yes sassc
      - run: make -C legacy www
